//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CHernyjj1412
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности ло.
    /// </summary>
    // *** Start programmer edit section *** (ДолжностиЛо CustomAttributes)

    // *** End programmer edit section *** (ДолжностиЛо CustomAttributes)
    [PublishName("Должности")]
    [AutoAltered()]
    [Caption("Должности")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностиЛоE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    [View("ДолжностиЛоL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    public class ДолжностиЛо : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ДолжностиЛо CustomMembers)

        // *** End programmer edit section *** (ДолжностиЛо CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ДолжностиЛо.Код CustomAttributes)

        // *** End programmer edit section *** (ДолжностиЛо.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ДолжностиЛо.Код Get start)

                // *** End programmer edit section *** (ДолжностиЛо.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ДолжностиЛо.Код Get end)

                // *** End programmer edit section *** (ДолжностиЛо.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДолжностиЛо.Код Set start)

                // *** End programmer edit section *** (ДолжностиЛо.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ДолжностиЛо.Код Set end)

                // *** End programmer edit section *** (ДолжностиЛо.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ДолжностиЛо.Наименование CustomAttributes)

        // *** End programmer edit section *** (ДолжностиЛо.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ДолжностиЛо.Наименование Get start)

                // *** End programmer edit section *** (ДолжностиЛо.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ДолжностиЛо.Наименование Get end)

                // *** End programmer edit section *** (ДолжностиЛо.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДолжностиЛо.Наименование Set start)

                // *** End programmer edit section *** (ДолжностиЛо.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ДолжностиЛо.Наименование Set end)

                // *** End programmer edit section *** (ДолжностиЛо.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностиЛоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиЛоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиЛоE", typeof(IIS.CHernyjj1412.ДолжностиЛо));
                }
            }
            
            /// <summary>
            /// "ДолжностиЛоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиЛоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиЛоL", typeof(IIS.CHernyjj1412.ДолжностиЛо));
                }
            }
        }
    }
}
